CREATE TABLE IF NOT EXISTS queued_scripts (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL,
    script TEXT NOT NULL,
    job_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS running_servers (
    job_id TEXT PRIMARY KEY,
    place_id TEXT NOT NULL,
    players INTEGER NOT NULL,
    last_ping TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS logged_games (
    id SERIAL PRIMARY KEY,
    place_id TEXT NOT NULL,
    job_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
